### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by ugintl** [chatziko/location-guard#13]
Youtube is not working in Pakistan. I installed location guard, but not working. YT is still detecting my location. Working on twitter though.

**Comment by chatziko** [comment]
Hello, youtube is detecting your country from your IP address. Location guard is not meant to protect you from this (try using Tor), instead it protects your accurate location from being disclosed through the javascript API. This is explained in the FAQ:

https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard
