### ISSUE TITLE
Uninstalled But My Real IP Address Still Being Hidden

### ISSUE THREAD

**Issue by PNightbird** [chatziko/location-guard#17]
I am in the USA and installed Location Guard into Firefox with a fixed location in Vietnam. I had to uninstall it because YouTube would not play some videos since it was detecting Vietnam as my location and there were copyright issues. However even after uninstalling Location Guard my location is still showing up as Vietnam when I check my IP address.

Can you please tell me what I need to do so that my real IP address is detected? Thank you. 
---
UPDATE:
The issue was resolved once I restarted my computer. Thank you.

**Comment by tambe** [comment]
Hola, instale gratis https://hola.org/ y podrá cambiar la IP cuando quiera o necesite, 
Un saludo.
