### ISSUE TITLE
problem setting a fixed location

### ISSUE THREAD

**Issue by danmihaipatrascu** [chatziko/location-guard#18]
Hi, the following bug it's related to the map API that you're using for fixed location. If you scroll out to maximum, and select a location from other "earth" than the middle one, the coordinates will have strange values. Maybe you can disable this API "feature", or you can set the minimum level for zoom. Keep up the good work!
![screenshot_position_guard_1](https://cloud.githubusercontent.com/assets/15957777/15074369/469fe60e-13a7-11e6-994c-56741e0d1b01.png)
![screenshot_position_guard_2](https://cloud.githubusercontent.com/assets/15957777/15074373/4a72f258-13a7-11e6-96ad-2c43bc17c589.png)

**Comment by Dexus** [comment]
Will this ever fixed? I mean its not some days ago...

**Comment by chatziko** [comment]
It's coming...

Kostas
sent from a mobile

**Comment by chatziko** [comment]
Thanks for reporting this! After a long wait, it's finally fixed in version 2.0.2 :smile:
