### ISSUE TITLE
User denied geolocation prompt

### ISSUE THREAD

**Issue by kyla963** [chatziko/location-guard#21]
This is probably a really ridiculous question, but I've been searching for an hours now and can't find an answer. 

When the demo started I accidentally said "no" when prompted to allow it to access my location. Obviously, now it won't work. I can't figure out how to go back and allow this. I've tried page info, but there is no permissions tab when I'm on this page. I'm lost. Help?

**Comment by chatziko** [comment]
Check [this for chrome](https://superuser.com/questions/591758/how-do-i-make-chrome-forget-a-no-to-geolocation-on-a-site) and [this for firefox](https://www.mozilla.org/en-US/firefox/geolocation/).
