### ISSUE TITLE
[feature request] Search box for fixed location

### ISSUE THREAD

**Issue by eldonzo** [chatziko/location-guard#22]
A search box in the page where you chose the fixed location would be of great use, it's very annoying to scroll the map around manually to find the exact place where you want to put the pin.

**Comment by metafaniel** [comment]
Indeed. It would be a great feature to be able to use coordinates to set the location. Please add a field to type exact latitude and longitude. Thanks and keep up the good work!

**Comment by chatziko** [comment]
Thanks for the suggestion!

This feature is added in version 2.0.2. There's now a search box that can be used either to search for a location, or to enter a "lat, lon" pair manually.
