### ISSUE TITLE
Disturbing Firefox Sync

### ISSUE THREAD

**Issue by Rictusempra** [chatziko/location-guard#23]
Location Guard sometimes disturbs Firefox Sync and another Email confirmation required.

**Comment by chatziko** [comment]
Strange, I cannot imagine how Location Guard could affect Firefox Sync.

But in any case, version 2.0.2 is completely rewritten using the new WebExtensions API, so this issue should hopefully be resolved.

So I'm closing it for now, feel free to reopen if the problem persists with version 2.0.2 or later.
