### ISSUE TITLE
https://yandex.ru/maps/

### ISSUE THREAD

**Issue by deadflower** [chatziko/location-guard#24]
Spoofing works well with google maps and demo page, BUT https://yandex.ru/maps/ can show real location

**Comment by chatziko** [comment]
Hello and thanks for reporting this issue.

I just tried https://yandex.ru/maps/ and Location Guard seemed to be working fine. Can you try to reset the settings and try again? If the problem still appears, please provide more details about the problem including detailed steps to reproduce it. Thanks!

**Comment by chatziko** [comment]
I'm closing this old issue cause I cannot reproduce the problem (https://yandex.ru/maps/ works fine for me). Feel free to reopen if the problem persists.
