### ISSUE TITLE
Fixed location bug in Europe?

### ISSUE THREAD

**Issue by VanAkemi** [chatziko/location-guard#25]
Hello @chatziko
In first place i would like to said that my message is long, please read all it.
In second place, sorry my bad english.
In third place i would like to said thank you!!! location-guard works in a nice way in Firefox, i'm so glad because now i can change my location in a site that i use everyday, but i'm having a small problem, i'm using location-guard only to change my location in a site, to change the location in the site i descovery how to know if will works or not the app location-guard, is super simple, i set some random location in fixed location map in location-guard and after i will in Firefox and I click on the browser footer '' update location or some like that '' ( where is my address in the browser, for example street name, city name, country name ) and after i refresh the page and bingo, challenge completed!! the browser show street name, city name, country name but it show a new information, ZIP code of the area, if it show all and ZIP code too, nice, my location changes in the site where i want, but when don't show the Zip Code together, don't changes my location in the site too where i want, the situation is, when you set some places in location-guard the location don't changes in the browser footer, and when have this situation if you refresh the page the location in Firefox simply freeze hehe just works again if you delete your whole Firefox historical ^^ but that is just a small detail, my real problem is, location-guard don't works when you try set any place in Europe and in Argentina ( south america country ) and i would like really to use some Europe location, can you help me, please?

**Comment by chatziko** [comment]
Thanks for reporting this issue!

This might be related to #18 which is now fixed in version 2.0.2.
Moreover, Firefox version 2.0.2 is rewritten using the new WebExtensions API, so chances are this issue no longer exists.

So I'm closing it for now, feel free to reopen if the problem persists with version 2.0.2 or later.
