### ISSUE TITLE
[Firefox] Eletrolysis support (e10s)

### ISSUE THREAD

**Issue by R4to0** [chatziko/location-guard#26]
Current Firefox release supports a multi process system called e10s, aka "Eletrolysis", which improve security and performance greatly.

Currently your plugin does not support this and forces Firefox to disable multiprocess feature. It would be awesome if you recompile your plugin with this feature.

![image](https://cloud.githubusercontent.com/assets/3608184/24885260/de2be8a6-1e23-11e7-879d-6a6e190d9616.png)

Here's the official wiki about it: https://wiki.mozilla.org/Electrolysis

Thanks!

**Comment by ExE-Boss** [comment]
They should just release the Chrome extension on [AMO](https://addons.mozilla.org) as a WebExtension (Firefox supports all the necessary APIs to make this work now)

**Comment by bkonetzny** [comment]
As of current Firefox Nightly (57.0a1), this extension can not be activated anymore, due to the described problems above. A shift to WebExtension should do the trick - any updates on this when this will be on AMO?

**Comment by paracetamolo** [comment]
Closing this one, the web-extension port is tracked by #30

**Comment by chatziko** [comment]
Please check #30 and test the new xpi if you can!
