### ISSUE TITLE
Is this extension dead?

### ISSUE THREAD

**Issue by D1001** [chatziko/location-guard#27]
It is listed as legacy when installed with the latest version of Firefox and hasn't been update since last year.

**Comment by paracetamolo** [comment]
In firefox 57 old add-ons not using the web extensions api will be disabled. We are planning an update to web extensions that should fix other issues as well.

**Comment by chatziko** [comment]
I'll make sure to update it to web extensions within a couple of weeks. It
shouldn't be hard since the same API is already used for Chrome.

**Comment by SlavMetal** [comment]
Any news on releasing the Firefox extension with support for new APIs?

**Comment by maybemi** [comment]
When can we expect a functioning version for FF57?

**Comment by paracetamolo** [comment]
The extension seems to be working fine in FF57 desktop with just a few tweaks, however we are having troubles with firefox for android. We are working on it and even if not feature complete we will update the addon before the 57 release.

**Comment by chatziko** [comment]
see #30 and test if you can!
