### ISSUE TITLE
Location Guard is still available in Opera?

### ISSUE THREAD

**Issue by kmacaro** [chatziko/location-guard#28]
hello, I try to install the location guard in opera and the page says 404 not found, where i can find the extension for opera? thanks

**Comment by chatziko** [comment]
I have no idea what's going on. The page indeed says 404 and I cannot log in my opera account. I'll see if I can contact someone from Opera to find out what happened.

**Comment by kmacaro** [comment]
Please let me know if you contact opera, want to use the extension and I cant, please help

**Comment by chatziko** [comment]
So, Opera decided to remove location guard without any warning. I re-submitted it in __november__, and is still waiting for approval.

This sucks, so for any opera user who might be interested, I will be providing zip files in the releases page for manual installation. It's actually quite simple, just download the `location-guard-opera-X.Y.Z.zip` file [from here](https://github.com/chatziko/location-guard/releases/latest), then drag-and-drop it to the extensions page (Ctrl-Shift-E).
