### ISSUE TITLE
Firefox: move to new jpm tool

### ISSUE THREAD

**Issue by paracetamolo** [chatziko/location-guard#3]
Starting with version 34 Firefox will support the new [jpm](https://github.com/mozilla/jpm) tool to manage dependencies npm-style and package add-ons. We should move to jpm eventually.
Useful links [1](http://work.erikvold.com/jetpack/2014/08/07/cfx-to-jpm.html) [2] (https://wiki.mozilla.org/Jetpack)

**Comment by paracetamolo** [comment]
It seems it is going to be supported from Firefox 38: 
https://blog.mozilla.org/addons/2015/02/26/jpm-replaces-cfx-for-firefox-38/

**Comment by chatziko** [comment]
Fixed by 5c319c37f608f4c9eb0686c39a482592f263122f
