### ISSUE TITLE
connect location guard to Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by stefan-paluch** [chatziko/location-guard#31]
I really like Location Guards and using it often, im also using Firefox Multi-Account Containers (https://github.com/mozilla/multi-account-containers), and there is my idea - connect fixed location with 'container' - eg. when tab is open in my 'work' container it should report New York fixed location , but in 'personal' tab browser get fixed location in Paris.
Its just a idea, i don't know if that interaction between webextension is this possible.

**Comment by chatziko** [comment]
I'm closing this old issue cause I don't think it will ever be implemented. It's an interesting idea, thanks for suggesting it, but:
1. It's too "niche", it concerns only one browser with a specific addon installed
2. I'm not sure whether it's even possible to interact with multi-account-containers.

Feel free to reopen though.
