### ISSUE TITLE
Location Guard version 2.1.0 and Firefox Quantum

### ISSUE THREAD

**Issue by davidhedlund** [chatziko/location-guard#32]
Location Guard version 2.1.0 and 2.1.1 is compatible with "[Firefox 55.0 and later](https://addons.mozilla.org/en-US/firefox/addon/location-guard/versions/)". I just installed Location Guard 2.1.0 on Firefox Quantum (Firefox 57), how is that possible?

WebExtensions should not be possible to install on Firefox 56 and earlier.

I'm confused.

**Comment by chatziko** [comment]
WebExtensions just became _obligatory_ in Firefox 57.

Firefox 55/56 support both legacy and WebExtensions.

Firefox 57 only supports WebExtensions.

**Comment by davidhedlund** [comment]
Thanks, that's exactly what I needed to hear.
