### ISSUE TITLE
Does this work in Linux?

### ISSUE THREAD

**Issue by chrisisbd** [chatziko/location-guard#35]
Does Location Guard work properly in Firefox on Linux?  It seems to install OK but I can't then get it to actually do anything.  The Location Guard icon on the pull-down menu in the address bar is disabled.

**Comment by chatziko** [comment]
Location Guard works fine on Linux, in fact all machines I own run Linux.

I'm closing this cause it likely refers to an old Firefox version. If you're still having troubles, please use the latest version and report what happens when you visit https://browserleaks.com/geo.
