### ISSUE TITLE
Does Location Guard change the location for Google Shopping?

### ISSUE THREAD

**Issue by chrisisbd** [chatziko/location-guard#36]
As per the subject, does Location Guard change the location for Google Shopping?  I suspect that it may not do so even though a couple of search results suggest that it does.  The location used by Google Shopping *isn't* entirely the same as that used in other areas of Google.

**Comment by chatziko** [comment]
No idea. Location Guard chages the location reported to th epage by javascript. How this location is used is up to the page.

Closing this cause it's not really a bug.
