### ISSUE TITLE
Nobody can see the Fixed Location checkbox

### ISSUE THREAD

**Issue by jidanni** [chatziko/location-guard#42]
Nobody can see the Fixed Location checkbox.
It is so dim.
There it is on the left!:
![6](https://user-images.githubusercontent.com/1230959/53803502-e660a280-3f7f-11e9-8e68-b9fe90b69347.jpg)
Even a U+25A1 WHITE SQUARE "□" would be an improvement.

**Comment by chatziko** [comment]
No plans/available time to change the UI, so I'm closing this for now. I'll keep it in mind in case the UI is redesigned in the future.
