### ISSUE TITLE
Some users use the app to IMPROVE location reporting accuracy

### ISSUE THREAD

**Issue by jidanni** [chatziko/location-guard#43]
When writing your faq.html#fixed etc. please remember the case of people who really want to report their real location, and are using this app to do that.

I.e., they are not "privacy maniacs", but instead "honest citizens" who live in remote mountains, that browsers never report very correctly. So as to improve accuracy to 100%, they are using your app.

So please add a paragraph for them. I am saying not all people are trying to hide their real location, some are the exact opposite. Yes they can still use the app fine, but please do mention them.

Indeed, the top phrase here on your GitHub is
> Hide your geographic location from websites.

**Comment by chatziko** [comment]
I'm closing this. I certainly understand the point, different people have different use-cases. But the main use of the addon is to hide one's location, so it makes sense to promote it in this way.
