### ISSUE TITLE
Some Machines Not Working

### ISSUE THREAD

**Issue by KingJohn2** [chatziko/location-guard#46]
For some reason this Main Pc will not work with fixed location. Each time I move the location icon I then use ipleak and click geo location, it pops up and asks me. cant stop it asking

Ok on laptop, both use Windows 10 updated, both same plug-ins (Sync)

**Comment by chatziko** [comment]
There was a bug (#47) that was affecting ipleak, it's fixed in v2.4.0 released today.

I'm closing this for now, feel free to reopen if you're still facing problems.
