### ISSUE TITLE
Update your MapBox Token

### ISSUE THREAD

**Issue by Exho1** [chatziko/location-guard#51]
The search functionality is currently nonfunctioning and returns a cryptic error because the API token with MapBox is expired or something of the sorts. I generated a new token on a branch of this project and then the search functionality was restored.

Line 1 in src/js/options.js is the constant variable mapboxToken, please update it or commit to a pricing plan so that the service can continue to be used

**Comment by chatziko** [comment]
When mapbox's free tiear limits are reached, it does't simply limit future requests, it completely blocks the account until you insert a credit card (which I'm not willing to do for a free addon).

I used a key from openrouteservice.org in the latest version, it now works again.
