### ISSUE TITLE
Location Guard Fails on Mac Catalina Public Beta

### ISSUE THREAD

**Issue by NormG1** [chatziko/location-guard#52]
Although the demo in Location Guard would seem to indicate the add-on is working properly sending the fixed location I have selected,, it is in fact broken on Catalina. 

Tested on both Chrome and Firefox. Tested on ipleak.net and iplocation. The geolocation being detected is either my actual physical location or the VPN server location but not the Location Guard location.

At the moment, Location Guard is non-functional and incompatible with Mac OSX v15 Catalina.

**Comment by chatziko** [comment]
ipleak.net and iplocation.net detect your coarse location from your IP. Location Guard is meant to protect the accurate location provided via javascript, not the coarse location obtained from the IP. There is a [related point](https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard) in the FAQ.

Note that ipleak.net can also detect your accurate location via javascript in the "Geolocation detection" section of the page, if you click on "Activate (may prompt an user permission on the browser)". Location guard should work when you click this button (but make sure you use v2.4.0 on Firefox).

I'm closing this for now, feel free to reopen if location guard is not working with the button mentioned above.
