### ISSUE TITLE
Does not work on Google

### ISSUE THREAD

**Issue by deepou** [chatziko/location-guard#55]
1) Shows the spoofed location via https://browserleaks.com/geo

2) Still shows my actual location when doing a Google search

Setup: Chrome 77 + Mac

**Comment by chatziko** [comment]
Pease see the FAQ below. Location Guard hides the location revealed by the browser through the JavaScript API (which is very accurate), Google has other sources of getting your location apart from the javascript API.

https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard
