### ISSUE TITLE
Search button doesn't work at the moment

### ISSUE THREAD

**Issue by Sam0099rurjei** [chatziko/location-guard#56]
Addon search button does not work at the moment.
![Screenshot (26)](https://user-images.githubusercontent.com/57544165/68538948-65f70a80-0374-11ea-917d-605ac04107ad.png)

**Comment by chatziko** [comment]
Likely a temporary issue of the provider unrelated to location guard. Can you try again now? It seems to be working for me.

**Comment by Sam0099rurjei** [comment]
Yeah it's working now.
Thanks.
