### ISSUE TITLE
Set a random location on each request

### ISSUE THREAD

**Issue by ghost** [chatziko/location-guard#57]
The obscure location-feature is very nice, but a random location-feature would be awesome. 

Feature: Every time a page requests my location give a random place in the world, doesn't even have to be in a populated place. 

Just to poison the data of the location tracking-algorithms.

**Comment by chatziko** [comment]
Thanks for the suggestion. I'm trying to keep the extension as simple as possible, so for the moment I'll keep the current options. But I might reconsider if more people ask for such a feature.
