### ISSUE TITLE
The following error occurred while retrieving your location:  Unknown error acquiring position

### ISSUE THREAD

**Issue by heyarne** [chatziko/location-guard#59]
**Describe the bug**

Hi, great extension idea! Unfortunately it doesn't fetch the location I configure, it just fails without providing any. When trying out the demo I get an `alert` as soon as I click on the location button:
```
The following error occurred while retrieving your location:

Unknown error acquiring position
```
There is nothing specific in the logs about this.

**To Reproduce**

1. Open the Location Guard addon page
2. Start the tutorial
3. Click next, then click on the icon
4. The error described above appears.

**Behaviour on browserleaks.com**

It can't fetch my location:

![image](https://user-images.githubusercontent.com/525780/73605958-3cc9cd00-45a5-11ea-85a6-cf2f2def66a2.png)

**Please complete the following information:**
 - OS: [e.g. Windows] Linux
 - Browser [e.g. Chrome, Firefox] Firefox
 - Version [e.g. 77] 72.0.2

**Comment by deejcunningham** [comment]
Had a similar issue on Arch, except browserleaks said my machine had it globally denied. This solution worked for me: https://wiki.archlinux.org/index.php/Firefox#Geolocation_does_not_work

**Comment by heyarne** [comment]
@deejcunningham solution worked! With the added benefit that it means one less google api call in my life. Thanks!
