### ISSUE TITLE
[Request] Add timezone spoofing

### ISSUE THREAD

**Issue by nim-a-k** [chatziko/location-guard#61]
Chrome's geo-location sensor allows spoofing the timezone and I think it should be in the scope of this extension to also be able to spoof timezone (based on location or manually). 
Since time zone is also a location-specific info that some websites use to track the user.

**Comment by chatziko** [comment]
Thanks for the suggestion. The addon has a very specific scope, protecting the javascript geolocation API (which gives very accurate information). The timezone is a different story (and much less accurate), so trying to also mess with it would make the extension quite confusing (and add a lot of complexity in the code).
