### ISSUE TITLE
Incorrect location reported macOS Chrome 87.0.4280.141

### ISSUE THREAD

**Issue by supersophie** [chatziko/location-guard#66]
**Describe the bug**
Real location is reported instead of location from LocationGuard

**To Reproduce**
Please include concrete steps to reproduce the behavior, this is the __most important__ information for fixing the problem:

1. Turn on NordVPN and set VPN endpoint to USA.
2. Set fixed location to New York
2. Enable location guard by pressing the icon in Chrome
3. go to mylocation.org
4. location reported as Brussels, Belgium

**Behaviour on location.org and abc.com/account**

If you experience a problem with Location Guard on some website, please report whether the same problem appears on https://browserleaks.com/geo or not.

Browserleaks.com/geo reports location as New York.

If not, please check that the website you're interested in uses javascript-based and not IP-based geolocation. Please read [the corresponding entry in the FAQ](https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard).

**Please complete the following information:**
 - OS: macOS 10.14.6 (18G7016)
 - Browser Chrome 
 - Version  87.0.4280.141

**Comment by chatziko** [comment]
mylocation.org uses IP-based or some other form of geolocation (usually not accurate). Location Guard protects against javascript-based geolocation (usually very accurate). It cannot protect against other forms of geolocation.

Please see the FAQ:
https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard
