### ISSUE TITLE
API Key missing - "The search service is not working right now. Please try again later."

### ISSUE THREAD

**Issue by Mattwmaster58** [chatziko/location-guard#67]
**Describe the bug**
The search functionality does not work.

**To Reproduce**
Please include concrete steps to reproduce the behavior, this is the __most important__ information for fixing the problem:
1. Go to fixed location
2. Click on the search button on the map
3. Search for anything
4. Observe error in UI and in dev tools

The search API endpoint is returning the following response:
```json
{
  "error": "Authorization field/api_key missing in request. If you do not have a token, please sign up for one at https://openrouteservice.org"
}
```

**Please complete the following information:**
 - OS: Windows
 - Browser: Firefox
 - Version: 87

I believe if there was an option to configure the API key instead of hard coding on [this line](https://github.com/chatziko/location-guard/blob/17336bb153ba6d2626e788d95abd7ce8046a4753/src/js/gui/options.js#L13) the issue would be mitigated.

**Comment by Mattwmaster58** [comment]
Another error is occuring now:
```json
{
  "error": "Daily quota reached or API key unauthorized"
}
```
I think putting the burden of API keys on the user may be the way to go here.

**Comment by virtual-orbis** [comment]
I am also receiving this error message from https://api.openrouteservice.org/
Failed to load resource: the server responded with a status of 403 ()
