### ISSUE TITLE
My location is not hidden

### ISSUE THREAD

**Issue by alkapwn3d** [chatziko/location-guard#76]
firefox 91.0.1 (64-bit)

https://ipleak.net/

I go here to see if my ip and location gets leaked by my browser

scroll down to "Geolocation Detection" and click activate

my real ip is hidden by my vpn but my real location is shown

**Comment by chatziko** [comment]
Please see the FAQ:
https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard

ipleak.net uses other forms of geolocation (probably IP-based, not accurate), Location Guard protects against javascript-based geolocation (the most accurate one).
