### ISSUE TITLE
Adding to Opera

### ISSUE THREAD

**Issue by lakrsrool** [chatziko/location-guard#77]
I realize this is not a "bug" hence is not the proper place for this topic - but I know of no other way to ask these questions.

I suppose I am expected to understand how to install extension on opera browser based on this:
Opera: download the location-guard-opera-X.Y.Z.zip file, then drag-and-drop it to the extensions page (Ctrl-Shift-E)

But I don't - "drag-and-drop" what?  and what does "Ctrl-Shift-E" supposed to do?

More understandable instructions for non-tech users would be helpful.

I have downloaded the zip-file (presumably the files should be extracted (or maybe not)....

Can you provide a more understandable (step-by-step) explanation on the method of installing the extension on Opera?

Why is this extension not simply available through the "normal" way extensions are added to Opera?

Sorry for not knowing more and sorry for posting in the wrong place - but w/out knowing any other way to contact I'm forced to try this.

If you have a better way to post this please explain this as well.

Thanks

**Comment by lakrsrool** [comment]
I can see no one is  going to get back to me using this venue - I'll post a follow-up to say that by adding the Opera "Install Chrome Extensions" this "Location Guard" extension (as well as any other Chrome extensions) can be installed on Opera very easily obviously - which I'd suggest should be the explanation for this add-on as far as (easily) adding it to Opera.

If anyone's paying attention - you can close this topic (as resolved in a much better way than the explanation on how to add this to Opera that is currently provided).

**Comment by chatziko** [comment]
Thanks for reporting this. Opera can now directly install extensions from the Chrome web store (natively, not even need for the "Install Chrome Extensions"). So I changed the instructions to just point to the chrome web store.
