### ISSUE TITLE
Geolocation DEMO's result in "User denied geolocation"

### ISSUE THREAD

**Issue by lakrsrool** [chatziko/location-guard#78]
Using the DEMO - while I get the message that "Location Guard was successfully installed" - the results of the DEMO says: 
The following error occurred while retrieving your location:
User denied geolocation prompt

**To Reproduce**
Do a DEMO (of any kind)

If applicable, add __screenshots__ to help explain your problem.

**Behaviour on browserleaks.com**

If you experience a problem with Location Guard on some website, please report whether the same problem appears on https://browserleaks.com/geo or not.
NOTE: using the above URL I get this result (same as in extensions DEMO): "01:19:41.160 [1] PERMISSION_DENIED – User denied Geolocation."

**Please complete the following information:**
 - OS: WIN10
 - Browser Firefox
 - Version 92.0

Also besides ALL of the DEMO (tests) I tried getting this same result ("Permission Denied" errors) - I cannot find a way to get the extensions ICON to display.  It is not available using "Custom" and does not display anywhere.  I've tried re-installing and/or turning the "Hide icon" on and off (enabled/disabled).

Screen-shot examples of DEMO tests:
![Location Guard DEMO example 1](https://user-images.githubusercontent.com/37479799/133974738-1d78fa44-544f-487a-bff5-6fa92a34b00b.png)
![Location Guard DEMO example 2](https://user-images.githubusercontent.com/37479799/133974756-03743133-9e6e-4abe-846e-c6da0338c802.png)

**Comment by chatziko** [comment]
This looks like a Firefox issue, is geolocation working in general?

Try to __uninstall__ Location Guard, and open https://browserleaks.com/geo 
Does geolocation work?

**Comment by chatziko** [comment]
Several fixes and improvements have been implemented this week, so I'm closing some old inactive issues.

If the problem persists in the latest version (v2.5.0) feel free to reopen the issue (and make sure to provide all the info mentioned in the bug template).

Thanks again for the report!
