### ISSUE TITLE
Fixed location not working on chrome?

### ISSUE THREAD

**Issue by sunny813** [chatziko/location-guard#79]
Hello, I use location guard's fixed location to use my YouTubeTV account and it has worked flawlessly for over a year now but as of last week it is no longer working. YTTV knows my actual location and is showing me channels based on that rather than my location guard location. Is there any fix to this?

**Comment by chatziko** [comment]
Does Fixed location work on https://browserleaks.com/geo ?

YouTube is likely using other methods of geolocation for finding your coarse location.
Location Guard is only protecting against javascript-based geolocation (the most accurate form).

Seel: https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard

**Comment by chatziko** [comment]
Several fixes and improvements have been implemented this week, so I'm closing some old inactive issues.

If the problem persists in the latest version (v2.5.0) feel free to reopen the issue (and make sure to provide all the info mentioned in the bug template).

Thanks again for the report!
