### ISSUE TITLE
fixed location not working

### ISSUE THREAD

**Issue by somejasper** [chatziko/location-guard#82]
I have fixed location on. I'm using a VPN. Yet the demo shows very close to my actual location.

Firefox 96.0.2, Windows 10 Home v. 21H2

**Comment by Gitoffthelawn** [comment]
I tried this extension for the first time the other day in Firefox 98.0.1.  I experienced the same issue.

**Comment by chatziko** [comment]
Can you please try it on https://browserleaks.com/geo   ?

Also make sure you click on the Locaction Guard icon in the URL bar and select "Set level for browserleaks.com" / "Use fixed location".

**Comment by somejasper** [comment]
OK, it is working -- I turned it on agan. I guess I have to check periodically to see if Fixed Location has been automatically turned off?Thank you

_______________
***@***.***

------- Original Message -------

**Comment by chatziko** [comment]
Not sure what happened, the settings should not turn off by themselves.

In any case, I'm closing this issue, feel free to open a new one if the problem reappears.
