### ISSUE TITLE
Map not showing, it does work but the map can't be seen on any browser.

### ISSUE THREAD

**Issue by olivercas01** [chatziko/location-guard#83]
**Describe the bug**
Map not showing

**To Reproduce**
Please include concrete steps to reproduce the behavior, this is the __most important__ information for fixing the problem:

If applicable, add __screenshots__ to help explain your problem.

**Behaviour on browserleaks.com**

If you experience a problem with Location Guard on some website, please report whether the same problem appears on https://browserleaks.com/geo or not.

If not, please check that the website you're interested in uses javascript-based and not IP-based geolocation. Please read [the corresponding entry in the FAQ](https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard).

**Please complete the following information:**
 - OS: Windows
 - Browser Chrome, Opera
 - Version 2.4.0

**Comment by chatziko** [comment]
Thanks for reporting. The problem was that chrome no longer displays openstreetmap tiles via http (needs https).

I pushed a new release, but it might take a while to appear in the chrome store.

**Comment by chatziko** [comment]
Version 2.4.1 (which fixes the issue) is now live in the chrome web store.
