### ISSUE TITLE
feature request: set country of origin, then add noise

### ISSUE THREAD

**Issue by C0NPAQ** [chatziko/location-guard#9]
I installed location guard, because I wanted websites to localize to north American territories. Currently they use my IP for localization, which is extremely obnoxious and often makes it very challanging to access content.

Since countries are huge, the added noise could be as huge as well.

**Comment by chatziko** [comment]
Hello and thanks for your report.

Setting the location to a different country is possible via the "Fixed Location" option. Note however that this [wont prevent IP-based geolocation](https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard).
